# Generated by Django 3.2.2 on 2021-06-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nus_module_code', models.CharField(max_length=10, unique=True)),
                ('nus_module_title', models.CharField(max_length=50)),
                ('nus_module_credit', models.IntegerField()),
            ],
        ),
    ]
