# Generated by Django 3.2.2 on 2021-06-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_university', models.CharField(max_length=50, unique=True)),
                ('partner_information', models.TextField()),
                ('partner_country', models.CharField(max_length=20)),
            ],
        ),
    ]
