# Generated by Django 3.2.2 on 2021-06-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='partner_university',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
