# Generated by Django 3.2.3 on 2021-06-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_university_partner_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='partner_university',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
