# Generated by Django 3.2.3 on 2021-06-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_university_partner_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nus_module_code', models.CharField(max_length=10, unique=True)),
                ('partner_university', models.CharField(max_length=100, unique=True)),
                ('partner_country', models.CharField(max_length=20)),
            ],
        ),
    ]
