# Generated by Django 3.2.3 on 2021-06-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_university_partner_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepair',
            name='nus_module_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='modulepair',
            name='partner_university',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='partner_university',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
